### ISSUE TITLE
(Require 'development) line breaks my config

### ISSUE THREAD

**Issue by jakubdonovan** [kpurdon/.emacs.d#8]
(require 'development) is causing my config to break. As soon as i comment that line out, everything is fine. Any ideas?

![](https://image.prntscr.com/image/G_wCZnKST9qvy9aRBLSXEg.png)

**-debug init**
Same error as above.

**And after i comment it out:**
![](https://image.prntscr.com/image/D0_XlIATSK2B15qERLyOmw.png)

![](https://image.prntscr.com/image/fiGDep6RRr6mZ-2rN3lvZw.png)

**Comment by kpurdon** [comment]
Sorry I missed this issue. `(require 'development)` is a pretty big load of things so a lot can fail in there. In this case it looks like an issue with enabling `flyspell-mode`. This is *probably* a missing dictionary dependency.

Make sure you have `aspell` installed: `brew install aspell`.
